### ISSUE TITLE
How do I set this to offline mode

### ISSUE THREAD

**Issue by mc-enjoyer** [ThomasOM/LiteLimbo#1]
Hi! I was wondering how I would set this to offline mode because without it the limbo server is basically useless, unable to be connected to velocity or bungeecord

**Comment by ThomasOM** [comment]
No authentication is done for anyone connecting, so it should work fine with velocity or bungee

**Comment by mc-enjoyer** [comment]
It does when it encrypts the session, it validates the session with mojang. Try running it with velocity it will say the servers in online mode, and when you directly try to connect to it it will not allow offline mode connections either. I fixed it by removing the encryption and skipping that process and directly accepting login events, on top  of that when using protocols <1.7.6 the limbo needs to respond to the login successful event with the dashes removed from the UUID or proxies wont accepts connections to it.

**Comment by ThomasOM** [comment]
I haven't tested this with velocity, but I see skipping encryption and instantly sending back the login success packet would work.
I'll add a startup parameter for this if you want to start up the server in offline mode.

**Comment by ThomasOM** [comment]
Should be properly supported now
https://github.com/ThomasOM/LiteLimbo/commit/9fccbae02374ba48c25ba36c160dde97f8d9f476

For any fixes regarding versions lower than 1.7.6, feel free to make a pull request

**Comment by mc-enjoyer** [comment]
Fixed the bug in [369ff37](https://github.com/ThomasOM/LiteLimbo/pull/2/commits/369ff37680e47c9840dcf66f2ab279c9d0904e15)
